### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by BennoG** [avancra/HvControllerGUI#1]
Where did you find the documentation for the serial protocol.
I own a SFT060N020 but without any documentation.
The python script crashes at the Q command response evaluation.

Can you add a PDF of the serial protocol to the repository ?

**Comment by avancra** [comment]
Hi! Thanks for your message. I am very sorry to reply so late to your issue. You probably have already solved the issue, but as it might possibly help other people in the future, I'll still answer to it. The serial protocol was provided in the documentation we received from Glassman together with the HV device itself. Unfortunately I am not able to share any documentation about the serial protocol because I do not have access to it anymore (I changed workplace). I can only advice to contact Glassman to get further information about it.
I can't tell much about the script crashing, but I can still add that this Python tool was designed for Glassman FJ series so there can be some specifications that differ with other device series and explain the crashing.
